<?php
session_start();
if (!isset($_SESSION["user_id"])) {
    header("Location: login.php");
    exit();
}

require_once __DIR__ . '/dompdf/autoload.inc.php';
use Dompdf\Dompdf;
use Dompdf\Options;

include 'db/config.php';

$user_id = (int)$_SESSION["user_id"];

$filterYear  = isset($_GET['year']) ? (int)$_GET['year'] : 0;
$filterMonth = isset($_GET['month']) ? (int)$_GET['month'] : 0;

$currentYear  = date('Y');
$currentMonth = date('m');

$isFiltered = ($filterYear > 0);

/* ================= DOMPDF ================= */
$options = new Options();
$options->set('defaultFont', 'DejaVu Sans');
$options->set('isHtml5ParserEnabled', true);

$dompdf = new Dompdf($options);
$dompdf->setPaper('A4', 'portrait');

/* ================= HTML BASE ================= */
$html = '
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
@page { margin: 120px 40px 80px 40px; }

body {
    font-family: DejaVu Sans, sans-serif;
    font-size: 12px;
    color:#111;
}

.header {
    position: fixed;
    top: -90px;
    left:0;
    right:0;
    text-align:center;
}

.footer {
    position: fixed;
    bottom: -50px;
    left:0;
    right:0;
    text-align:center;
    font-size:10px;
    color:#666;
}

table {
    width:100%;
    border-collapse:collapse;
    margin-top:15px;
}

th {
    background:#cce4ff;
    color:black;
    padding:8px;
    font-size:11px;
}

td {
    padding:7px;
    border-bottom:1px solid #ddd;
    font-size:11px;
}

.table-heading {
    background:#f3f4f6;
    color:#111;
    font-size:14px;
    font-weight:bold;
    text-align:left;
    padding:10px;
}

.amount-income { color:#059669; font-weight:bold; }
.amount-expense { color:#dc2626; font-weight:bold; }

tfoot td {
    font-weight:bold;
    background:#f9fafb;
}

.tfoot-right {
    text-align:right;
}

.section {
    margin-bottom:35px;
}
</style>
</head>

<body>

<div class="header">
    <h1>Financial Report</h1>
</div>

<div class="footer">
    Generated by Expense Tracker
</div>
';

/* =====================================================
   ================= FILTERED REPORT ===================
   ===================================================== */
if ($isFiltered) {

    $title = $filterYear;
    if ($filterMonth) {
        $title = date('F', mktime(0,0,0,$filterMonth,1)) . " $filterYear";
    }

    $where = "WHERE user_id='$user_id' AND YEAR(date)='$filterYear'";
    if ($filterMonth) {
        $where .= " AND MONTH(date)='$filterMonth'";
    }

    $sql = "
        SELECT 'Income' AS type, source AS title, description, amount, date FROM income $where
        UNION ALL
        SELECT 'Expense' AS type, category AS title, description, amount, date FROM expenses $where
        ORDER BY date DESC
    ";

    renderTableWithHeading("Filtered Report ($title)", $conn->query($sql), $html);

}
/* =====================================================
   ================= NO FILTER MODE =====================
   ===================================================== */
else {

    /* ================= THIS MONTH ================= */
    $sql = "
        SELECT 'Income' AS type, source AS title, description, amount, date FROM income
        WHERE user_id='$user_id' AND YEAR(date)='$currentYear' AND MONTH(date)='$currentMonth'
        UNION ALL
        SELECT 'Expense' AS type, category AS title, description, amount, date FROM expenses
        WHERE user_id='$user_id' AND YEAR(date)='$currentYear' AND MONTH(date)='$currentMonth'
        ORDER BY date DESC
    ";
    renderTableWithHeading("This Month (".date('F Y').")", $conn->query($sql), $html);

    /* ================= PREVIOUS MONTHS ================= */
    $sql = "
        SELECT 'Income' AS type, source AS title, description, amount, date FROM income
        WHERE user_id='$user_id'
          AND (YEAR(date) < '$currentYear'
          OR (YEAR(date)='$currentYear' AND MONTH(date) < '$currentMonth'))
        UNION ALL
        SELECT 'Expense' AS type, category AS title, description, amount, date FROM expenses
        WHERE user_id='$user_id'
          AND (YEAR(date) < '$currentYear'
          OR (YEAR(date)='$currentYear' AND MONTH(date) < '$currentMonth'))
        ORDER BY date DESC
    ";

    $res = $conn->query($sql);
    $grouped = [];
    while ($r = $res->fetch_assoc()) {
        $grouped[date('F Y', strtotime($r['date']))][] = $r;
    }

    foreach ($grouped as $month => $rows) {
        renderTableArrayWithHeading("Previous Month - $month", $rows, $html);
    }

    /* ================= THIS YEAR ================= */
    $sql = "
        SELECT 'Income' AS type, source AS title, description, amount, date FROM income
        WHERE user_id='$user_id' AND YEAR(date)='$currentYear'
        UNION ALL
        SELECT 'Expense' AS type, category AS title, description, amount, date FROM expenses
        WHERE user_id='$user_id' AND YEAR(date)='$currentYear'
        ORDER BY date DESC
    ";
    renderTableWithHeading("This Year ($currentYear)", $conn->query($sql), $html);

    /* ================= PREVIOUS YEARS ================= */
    $sql = "
        SELECT 'Income' AS type, source AS title, description, amount, date FROM income
        WHERE user_id='$user_id' AND YEAR(date) < '$currentYear'
        UNION ALL
        SELECT 'Expense' AS type, category AS title, description, amount, date FROM expenses
        WHERE user_id='$user_id' AND YEAR(date) < '$currentYear'
        ORDER BY date DESC
    ";

    $res = $conn->query($sql);
    $grouped = [];
    while ($r = $res->fetch_assoc()) {
        $grouped[date('Y', strtotime($r['date']))][] = $r;
    }

    foreach ($grouped as $year => $rows) {
        renderTableArrayWithHeading("Previous Year - $year", $rows, $html);
    }
}

/* ================= RENDER ================= */
$html .= '</body></html>';

$dompdf->loadHtml($html);
$dompdf->render();
$dompdf->stream("financial_report.pdf", ["Attachment" => true]);
exit;


/* ================= HELPERS ================= */

function renderTableWithHeading($heading, $res, &$html) {
    $rows = [];
    while ($r = $res->fetch_assoc()) {
        $rows[] = $r;
    }
    renderTableArrayWithHeading($heading, $rows, $html);
}

function renderTableArrayWithHeading($heading, $rows, &$html) {

    if (empty($rows)) return;

    $inc = 0;
    $exp = 0;

    $html .= '
    <table>
        <thead>
            <tr>
                <th colspan="6" class="table-heading">'.$heading.'</th>
            </tr>
            <tr>
                <th>#</th>
                <th>Type</th>
                <th>Category</th>
                <th>Description</th>
                <th>Amount</th>
                <th>Date</th>
            </tr>
        </thead>
        <tbody>';

    $i = 1;
    foreach ($rows as $r) {

        if ($r['type'] === 'Income') {
            $inc += $r['amount'];
        } else {
            $exp += $r['amount'];
        }

        $html .= '
        <tr>
            <td>'.$i++.'</td>
            <td>'.$r['type'].'</td>
            <td>'.htmlspecialchars($r['title']).'</td>
            <td>'.htmlspecialchars($r['description'] ?? '-').'</td>
            <td class="'.($r['type']=='Income'?'amount-income':'amount-expense').'">
                ₹ '.number_format($r['amount'],0).'
            </td>
            <td>'.date('d M Y', strtotime($r['date'])).'</td>
        </tr>';
    }

    $html .= '
        </tbody>
        <tfoot>
            <tr>
                <td colspan="6" class="tfoot-right">
                    Income: ₹ '.number_format($inc,0).' |
                    Expense: ₹ '.number_format($exp,0).' |
                    Balance: ₹ '.number_format($inc - $exp,0).'
                </td>
            </tr>
        </tfoot>
    </table>

    <div class="section"></div>';
}
